[package]
name = "markdown-it-sample"
version = "0.1.0"
edition = "2021"
authors = ["Koji Onishi <fursich0@gmail.com>"]
license = "MIT"
publish = false

[dependencies]
markdown-it     = ">= 0.6"
url             = ">= 2.5"
clap  =  { version = ">= 4.5", features = ["derive"] }
